Bio\BiodataBundle\Entity\Personal:
    type: entity
    table: null
    repositoryClass: Bio\BiodataBundle\Repository\PersonalRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        gender:
            type: boolean
        weight:
            type: float
        height:
            type: float
        scolarity:
            type: integer
        birthdate:
            type: date
    lifecycleCallbacks: {  }
