<?php

namespace Bio\BiodataBundle\Repository;

/**
 * PsychEvalFreqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PsychEvalFreqRepository extends \Doctrine\ORM\EntityRepository
{
}
