<?php

namespace Bio\BiodataBundle\Repository;

/**
 * PsychEvalAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PsychEvalAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
