eval_freq_index:
    path:     /
    defaults: { _controller: "BioBiodataBundle:PsychEvalFreq:index" }
    methods:  GET

eval_freq_show:
    path:     /{id}/show
    defaults: { _controller: "BioBiodataBundle:PsychEvalFreq:show" }
    methods:  GET

eval_freq_new:
    path:     /new
    defaults: { _controller: "BioBiodataBundle:PsychEvalFreq:new" }
    methods:  [GET, POST]

eval_freq_edit:
    path:     /{id}/edit
    defaults: { _controller: "BioBiodataBundle:PsychEvalFreq:edit" }
    methods:  [GET, POST]

eval_freq_delete:
    path:     /{id}/delete
    defaults: { _controller: "BioBiodataBundle:PsychEvalFreq:delete" }
    methods:  DELETE
