eval_area_index:
    path:     /
    defaults: { _controller: "BioBiodataBundle:PsychEvalArea:index" }
    methods:  GET

eval_area_show:
    path:     /{id}/show
    defaults: { _controller: "BioBiodataBundle:PsychEvalArea:show" }
    methods:  GET

eval_area_new:
    path:     /new
    defaults: { _controller: "BioBiodataBundle:PsychEvalArea:new" }
    methods:  [GET, POST]

eval_area_edit:
    path:     /{id}/edit
    defaults: { _controller: "BioBiodataBundle:PsychEvalArea:edit" }
    methods:  [GET, POST]

eval_area_delete:
    path:     /{id}/delete
    defaults: { _controller: "BioBiodataBundle:PsychEvalArea:delete" }
    methods:  DELETE
